spring.application.name=settlement-funding
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/kursi}
spring.datasource.username=${DB_USERNAME:kursi}
spring.datasource.password=${DB_PASSWORD:kursi}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
